{
    "openapi": "3.0.3",
    "info": {
        "title": "API Product",
        "description": "API para manipulação de produtos do eccomerce.",
        "contact": {
            "email": "ecomm@gmail.com"
        },
        "version": "1.0.0"
    },
    "servers": [
        {
            "url": "http://localhost:3001",
            "description": "API de teste"
        }
    ],
    "paths": {
        "/products": {
            "post":{
                 "tags": [
                    "Product"
                ],
                "summary": "Creates a product",
                "description": "Given provided data, creates a product in the database",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Product"
                            },
                            "examples": {
                                "product": {
                                    "value": {
                                        "produto": {
                                            "nome": "name",
                                            "valor": 15,
                                            "quantidade": 1,
                                            "descricao": "string",
                                            "categoria": "string",
                                            "caracteristicas": [
                                                {
                                                    "nome": "string",
                                                    "descricao": "string"
                                                }
                                            ],
                                            "imagens": [
                                                {
                                                    "url": "string",
                                                    "descricao": "string"
                                                }
                                            ]
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "400": {
                        "description": "Error creating product!"
                    },
                    "201": {
                        "description": "Created",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "products": {
                                        "value": {
                                            "id": "6d607f6a-3625-45df-884a-d2a479680393",
                                            "createdDate": "2022-12-22",
                                            "produto": {
                                                "nome": "name",
                                                "valor": 15,
                                                "quantidade": 1,
                                                "descricao": "string",
                                                "categoria": "string",
                                                "caracteristicas": [
                                                    {
                                                        "nome": "name",
                                                        "descricao": "string"
                                                    }
                                                ],
                                                "imagens": [
                                                    {
                                                        "url": "url da imagem",
                                                        "descricao": "string"
                                                    }
                                                ]
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "get": {
                "tags": [
                    "Product"
                ],
                "summary": "list of registered products",
                "description": "This route will be responsible for listing the registered products",
                "responses": {
                    "500": {
                        "description": "Error fetching products!"
                    },
                    "200": {
                        "description": "success",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "products": {
                                        "value": {
                                            "id": "6d607f6a-3625-45df-884a-d2a479680393",
                                            "createdDate": "2022-12-22",
                                            "produto": {
                                                "nome": "nome do produto",
                                                "valor": 15,
                                                "quantidade": 1,
                                                "descricao": "string",
                                                "categoria": "string",
                                                "caracteristicas": [
                                                    {
                                                        "nome": "nome do produto",
                                                        "descricao": "string"
                                                    }
                                                ],
                                                "imagens": [
                                                    {
                                                        "url": "url da imagem",
                                                        "descricao": "imagem"
                                                    }
                                                ]
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "Product": {
                "type": "object",
                "properties": {
                    "nome": {
                        "type": "string"
                    },
                    "valor": {
                        "type": "number"
                    },
                    "quantidade": {
                        "type": "number"
                    },
                    "descricao": {
                        "type": "string"
                    },
                    "categoria": {
                        "type": "string"
                    },
                    "caracteristicas": {
                        "type": "array",
                        "items": {
                            "nome": "string",
                            "descricao": "string"
                        }
                    },
                    "imagens": {
                        "type": "array",
                        "items": {
                            "url": "string",
                            "descricao": "string"
                        }
                    }
                }
            }
        }
    }
}